### ISSUE TITLE
Emulator initial resolution is ignored after "Recycle" activity

### ISSUE THREAD

**Issue by zvasilius** [DanielHarrod/AppTestStudio#44]
I've configured app resolution to 640x360 (NoxPlayer), it's working fine, but after completion 'Recycle' activity emulator is started with different resolution (I suppose default one)

**Comment by DanielHarrod** [comment]
Hi zvasilius,

Thank you for reporting this issue, I was able to reproduce it.  If you run from source code, pull the latest, I'll made an update later today if it's being run from the installation.

Thanks,

Daniel

**Comment by DanielHarrod** [comment]
Hi zvasilius,

If you install version 12 this issue has been fixed.

Thanks,

Daniel
