### ISSUE TITLE
Future Request: Add Proxy support 

### ISSUE THREAD

**Issue by muratulashozturk** [DanielHarrod/AppTestStudio#48]
add setting system proxy future If possible

**Comment by DanielHarrod** [comment]
Hi Murat,

Thank you for your suggestion.  Some of the best features in ATS have come from suggestions.  

I don't have a lot of experience with the use of proxy.  ATS intentionally does not communicate or store any information remotely to maintain user privacy.  All data is stored locally in readable XML files and images.

However, I think that it's possible to implement an automated solution with multiple proxy through setting up multiple instances of [NoxPlayer](https://www.bignox.com/blog/how-to-run-multiple-android-instances-with-nox-app-player/) with each one using the same proxy or multiple proxy.  As ATS can be configured to automate specific instances of the emulator which would then provide the benefits of proxy.

The other option that comes to mind is applications such as the google chrome browser can be launched and passed command line arguments that set proxy for that instance.  [Link](https://www.chromium.org/developers/design-documents/network-settings/) for example.
![image](https://user-images.githubusercontent.com/4130489/203840452-0d410f06-a243-47ed-996c-9413000dad19.png)
*When testing I found that in ATS that the Platform: Application, Parameters (4) field was not being saved.  This will be corrected in an upcoming build v16, or available in source code after it's been committed.  

Thanks,

Daniel
